version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: ${PUID} # PGID: ${PGID} -- optional, your user id
      PGID: ${PGID}
    ports:
      - ${HOMEPAGE_PORT}:3000
    volumes:
      - ${CONFIG_PATH}:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped